name: Accounts Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  Build-And-Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Test git
        run: |
          git fetch
          git log --oneline -5
      - name: Check Affected
        run: npx nx show projects --affected --base=${{ github.event.before }} | grep -q '@xpkg/accounts'
      - name: Build
        if: success()
        run: |
          echo 'Building'
          npx nx run --parallel=3 @xpkg/accounts:build 