name: Accounts Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build-And-Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install
        run: npm ci --include=dev --verbose
      - name: Check Affected
        continue-on-error : true
        run: npx nx show projects --affected --base=${{ github.event.before }} | grep -q '@xpkg/accounts'
      - name: Lint
        run: npx nx run --verbose @xpkg/accounts:check-lint
      - name: Build
        if: ${{ success() }}
        working-directory: './frontend/accounts'
        # run: npx nx run --verbose --parallel=3 @xpkg/accounts:build
        run: |
          npx nx run --verbose @xpkg/frontend-util:build
          npx nx run --verbose @xpkg/validation-util:build
          npx nx run --verbose @xpkg/auth-util:build
          npm run build