name: Accounts Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build-And-Upload:
    runs-on: macos-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: npm
      - name: Cache NX/pip
        uses: actions/cache/restore@v4
        with:
          path: |
            .nx/cache
            /Users/runner/Library/Caches/pip
          key: ${{ runner.os }}-nx
      - name: Install
        run: npm ci --include=dev --verbose
      - name: Check Affected
        continue-on-error : true
        run: npx nx show projects --affected --base=${{ github.event.before }} | grep -q '@xpkg/accounts'
      - name: Lint
        run: npx nx run @xpkg/accounts:check-lint
      - name: Build
        if: ${{ success() }}
        working-directory: './frontend/accounts'
        run: npx nx run --parallel=3 @xpkg/accounts:build
      - name: Delete Contents
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          silent: false
          id: delete-contents
          command: os object bulk-delete --namespace-name ${{ vars.OCI_OBJECT_STORAGE_NAMESPACE }} --bucket-name ${{ vars.ACCOUNTS_BUCKET_NAME }}
      - name: Upload Contents
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          silent: false
          id: upload-contents
          command: os object bulk-upload --src-dir frontend/accounts/build --namespace-name ${{ vars.OCI_OBJECT_STORAGE_NAMESPACE }} --bucket-name ${{ vars.ACCOUNTS_BUCKET_NAME }} --no-follow-symlinks --overwrite --parallel-upload-count 15