name: Accounts Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Build-And-Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Check Affected
        run: npx nx show projects --affected --base=HEAD~1 | grep -q '@xpkg/accounts'
      - name: Build
        run: |
          echo 'Building'
          npx nx run --parallel=3 @xpkg/accounts:build 