name: CI/CD
on:
  workflow_dispatch: 
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ArkinSolomon/xpkg-web-apps/.github/workflows/setup.yml@master
      - run: npx nx affected -t check-lint --parallel=3
  build:
    needs: lint
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: ArkinSolomon/xpkg-web-apps/.github/workflows/setup.yml@master
      - run: git branch --track master origin/master
      - run: npx nx affected -t build --parallel=3