name: Setup

on:
  workflow_call:

jobs:
  setup:
   name: Setup
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 21.1
        cache: 'npm'
    - run: npx nx run-many -t install-deps
    - uses: nrwl/nx-set-shas@v3